FROM centos:centos7
LABEL maintainer="IBM OMS Performance Team"
RUN /bin/bash -c "yum -y update; \
yum -y install vim; \
yum -y install wget; \
wget https://bintray.com/loadimpact/rpm/rpm -O bintray-loadimpact-rpm.repo; \
mv bintray-loadimpact-rpm.repo /etc/yum.repos.d/; \
yum -y install k6; \
echo $'[gcsfuse]\nname=gcsfuse (packages.cloud.google.com)\nbaseurl=https://packages.cloud.google.com/yum/repos/gcsfuse-el7-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg\n\thttps://packages.cloud.google.com/yum/doc/rpm-package-key.gpg' > /etc/yum.repos.d/gcsfuse.repo; \
yum -y install gcsfuse"


