apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: grafana
          image: eu.gcr.io/evocative-bus-288811/grafana6:v1
          env:
            - name: "GF_PATHS_DATA"
              value: "/var/lib/grafana-db"
          volumeMounts:
          - name : grafana-persistent-storage
            mountPath : /var/lib/grafana-db
      volumes:
        - name: grafana-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-grafana
            
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-service
spec:
  ports:
  - port: 3001
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: grafana