apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influx
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: eu.gcr.io/evocative-bus-288811/influxdb:v1
          volumeMounts:
          - name : influxdb-persistent-storage
            mountPath : /var/lib/influxdb
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-influx
            
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb-service
spec:
  ports:
  - port: 9091
    targetPort: 8086
  type: LoadBalancer
  selector:
    app: influxdb